services:
  # 1. Веб-сервер / Reverse Proxy
  nginx:
    image: nginx:1.26-alpine3.20
    ports:
      - "80:80"
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro #(read only)
    depends_on:
      - frontend
      - backend

  # 2. Фронтенд (Next.js)
  frontend:
    build:
      context: ../ppt-front
      dockerfile: Dockerfile

  # 3. Бэкенд (Laravel + Filament)
  backend:
    build:
      context: ../ppt-back
      dockerfile: Dockerfile
    # Передаем переменные из .env внутрь контейнера
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_SCHEME}://${APP_DOMAIN}
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${PG_DB}
      - DB_USERNAME=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres

  # 4. База данных PostgreSQL
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: